### ISSUE TITLE
just does not work, listening by port 1701

### ISSUE THREAD

**Issue by uranio-235** [hwdsl2/setup-ipsec-vpn#609]
```
ipsec-vpn-server | Redirecting to: /etc/init.d/ipsec start
ipsec-vpn-server | Starting pluto IKE daemon for IPsec: Initializing NSS database
ipsec-vpn-server |
ipsec-vpn-server | xl2tpd[1]: Not looking for kernel SAref support.
ipsec-vpn-server | xl2tpd[1]: Using l2tp kernel support.
ipsec-vpn-server | xl2tpd[1]: xl2tpd version xl2tpd-1.3.12 started on ipsec-vpn-server PID:1
ipsec-vpn-server | xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
ipsec-vpn-server | xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
ipsec-vpn-server | xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
ipsec-vpn-server | xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
ipsec-vpn-server | xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701
```

and this is my docker-compose 

```
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    environment:
      - VPN_IPSEC_PSK=mypsk
      - VPN_USER=myuser
      - VPN_PASSWORD=mypassword
      - VPN_DNS_SRV1=1.1.1.1
      - VPN_DNS_SRV2=8.8.8.8
```

Firewall ports open
