### ISSUE TITLE
Unable to ping other docker containers after setting DNS

### ISSUE THREAD

**Issue by ztj1993** [hwdsl2/setup-ipsec-vpn#741]
I've set up DNS, but I still can't Ping other containers. In the same network environment, you can ping by entering the shell.

How to configure this situation?

```
    image: hwdsl2/ipsec-vpn-server
    privileged: true
    dns: 127.0.0.11
    environment:
      - VPN_DNS_SRV1=127.0.0.11
      - VPN_DNS_SRV2=127.0.0.11
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
```

Test for a long time, help to see, thank you!
